In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(4,)

In [6]:
b = np.array([[1,2,3,4],
              [5,6,7,8]])

In [7]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
b.shape

(2, 4)

In [9]:
b_T = b.T
b_T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [10]:
np.dot(b, b_T)

array([[ 30,  70],
       [ 70, 174]])

### Some Basic Functions

In [11]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [12]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [13]:
print(x+y)

print(x-y)

print(x*y)

print(x/y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [14]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [15]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Randoms

In [18]:
ar = np.arange(0, 25, 2)
ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [19]:
ar = np.linspace(0, 10, 50)
ar

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
matrix = np.random.randint(10, 100, (5,5))
matrix

array([[68, 67, 99, 31, 17],
       [55, 58, 13, 82, 50],
       [87, 66, 97, 67, 39],
       [17, 62, 19, 85, 81],
       [44, 15, 62, 71, 30]])

In [21]:
print(np.max(matrix))
print(np.min(matrix))

99
13


In [22]:
a = np.array([5,7,2,5,7,5,3,4,5,7,32,10])

In [23]:
print(np.argmin(a))
print(np.argmax(a))

2
10


In [24]:
np.unique(a, return_counts=True)

(array([ 2,  3,  4,  5,  7, 10, 32]),
 array([1, 1, 1, 4, 3, 1, 1], dtype=int64))

In [25]:
r = np.random.randn(5,10)

In [26]:
r

array([[ 0.51485217,  0.45369792,  1.25322035,  0.07223216, -0.39003201,
        -0.41849673,  3.34186642, -0.28168342, -0.74341301,  0.64269014],
       [-0.19271529, -0.77106939, -0.5912388 , -1.04758309,  1.84402865,
         0.02401111, -1.16306131,  2.01285562, -0.40464132,  0.21328657],
       [-1.78756474, -0.29766913,  1.38830188, -0.5484929 , -0.2482417 ,
         2.24868988,  0.10378146, -0.72664386,  0.7190925 , -0.81765619],
       [ 0.47051626,  1.97640918, -0.13231696,  0.24016271,  0.08021713,
        -0.86725781, -0.51787659,  0.53423634,  1.45969764,  1.09729967],
       [ 0.67446673,  0.83951367,  0.76655655, -0.74968495,  0.97623083,
        -0.11818176,  0.48289529,  0.88287709,  1.20161175,  1.46232819]])

In [27]:
print("mean : %0.2f"%r.mean())
print("std : %0.2f"%r.std())

mean : 0.30
std : 1.00


## Slicing

In [28]:
matrix = np.random.randint(0,100,size=(5,5))

In [29]:
matrix

array([[73, 57, 58, 66, 34],
       [56, 33, 19, 73, 56],
       [46, 89, 68,  7, 26],
       [ 2, 63,  9, 81, 13],
       [78, 30, 57, 41, 89]])

In [30]:
matrix[1:3, 1:3]

array([[33, 19],
       [89, 68]])

### Reshaping

In [31]:
a = np.random.randint(0,100, (4,12))

In [32]:
a.shape

(4, 12)

In [33]:
a

array([[54,  4, 24, 12, 54, 91, 69, 27, 21, 60, 57, 80],
       [30, 57, 75, 92, 78, 92, 11, 73, 83, 79, 57, 74],
       [79, 49, 13, 86, 15,  5, 74, 25, 45, 34, 19, 91],
       [30, 84, 52, 78, 62,  3,  1, 58, 86, 59, 48, 39]])

In [34]:
a = a.reshape((8,6))

In [35]:
a.shape

(8, 6)

In [36]:
a = a.reshape((3,-1))

In [37]:
a.shape

(3, 16)

## Broadcasting

In [38]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [39]:
a + 10

array([11, 12, 13, 14])

In [40]:
a = np.array([[1,2,3],
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a + [1,2,3]

array([[2, 4, 6],
       [5, 7, 9]])

In [42]:
a + [[1],[2]]

array([[2, 3, 4],
       [6, 7, 8]])

# Scientific Calculations

In [43]:
np.sin(40)

0.7451131604793488

In [44]:
np.tan(40)

-1.117214930923896

In [45]:
a = np.array([[1,2],[3,4]])

np.linalg.pinv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [46]:
b = np.array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [47]:
np.dot(a,b)

array([[1., 0.],
       [0., 1.]])